### ISSUE TITLE
There are some unavailable help contents in the "about.txt" of some languages

### ISSUE THREAD

**Issue by xiaopangju** [Tampermonkey/tampermonkey-i18n#177]
There are some contributors created a file called `about.txt` in their own languages, but some of them ask the users to visit the Tampermonkey Forum to make suggestions about the translation(like [Japanese](https://github.com/Tampermonkey/tampermonkey-i18n/blob/master/ja/about.txt) . But the forum is down, so some languages' users are unable to make suggestions to the contributors.

Can you contact the contributors in these languages ​​and ask them to provide usable contact information, or delete the content about the Tampermonkey Forum?

here is a list of the `about.txt` files include Tampermonkey Forum

- https://github.com/Tampermonkey/tampermonkey-i18n/blob/master/ja/about.txt
- https://github.com/Tampermonkey/tampermonkey-i18n/blob/master/fr/about.txt
- https://github.com/Tampermonkey/tampermonkey-i18n/tree/master/pl/about.txt
@shirayuki Can you fix this problem in Japanese locate?

**Comment by omerien** [comment]
I'm French, I will help for fr file.

**Comment by xiaopangju** [comment]
thanks

Yours faithfully,
Haoran Du
________________________________

**Comment by JAGulin** [comment]
@hawkeye116477 (pl) @zek0faws (fr)
https://github.com/Tampermonkey/tampermonkey-i18n/community
> But the forum is down, so some languages' users are unable to make suggestions to the contributors.

The forum says "temporary down" so perhaps not a big issue. 
In addition, I would consider this a collaborative effort, so when lacking other contact ways, feel free to submit suggested changes as per readme. 
I suppose it would help to get quality approval from the current translator or community, but they could monitor this git for change requests. For language related discussions and suggestions it would also be possible to promote this github issue tracker as the place to go. Perhaps that particular forum page could be redirected automatically.

@derjanb  How do you currently review which changes that can be accepted or not? Is approval from the "official" translator required? Could you provide guideline to what content that is appropriate in the "about.txt"?

**Comment by xiaopangju** [comment]
In fact, there a are few PRs merged after reviewing by me. Sometimes a bad translation  will also merged after asked change by me, like #197 .

**Comment by zek0faws** [comment]
Every one is free to make a PR to update the language.
The PR will be (normally) reviewed by other people. You can ping them in your PR using the "@" in the contrib file

The `@contrib`is not ment to be the official translator, but should be the people which updates (aka contrib) to the language updates.

The forum url were put in the files when @derjanb create the repo. Nobody change them, even if the subforum is not active anymore.

And yes, the forum is down for now due to GDPR and should be back someday.
Feel free to update your language, if anyone is not happy with your translation and see the github, they will comment your PR
