### ISSUE TITLE
Split `enabled` term per context.

### ISSUE THREAD

**Issue by marsjaninzmarsa** [Tampermonkey/tampermonkey-i18n#62]
Term [_Enabled_](https://github.com/Tampermonkey/tampermonkey-i18n/blob/193b3902a3429c9982d515c76161ce31dbe96d1d/en/messages.json#L540) should be translated differently depending on context: eg. in Polish as _Włączony/Aktywny_ in terms of scripts, and _Włączenie/Aktywacja_ in terms of activation date (sorting order), possibly also different in other unnoticed places, need term clarification.

**Comment by derjanb** [comment]
Hmm, can you please tell me where it is used in in terms of activation date? I've checked the source and every usage I found should be related to a/the scripts enabled state. Thanks, Jan.

**Comment by derjanb** [comment]
I understand that different languages have subtle differences which are not necessarily obvious to other language speakers. That's why please correct me if I'm wrong. I checked this again and "Enabled" is always used in terms of the current state. The on/off slider title says "Enabled" if the script already is turned on. It expresses the current state, not what will happen once the element is clicked. Sorting by "Enabled" state does the same, it causes the table to be sorted by the current state.
